package uwu.openjfx;

public enum RoyalType {
    PLAYER, WALL, DOOR, ENEMY, TRAP_TRIGGER, TRAP, POINT, PLAYERATTACK, ENEMYATTACK, COIN,
    DROPPEDITEM, PPWall, CHEST, NPC, FINALDOOR, SPIKE, SMASHEDGROUND;

}